export const SET_IS_EXCHANGE_RATE_LOADING = "SET_IS_EXCHANGE_RATE_LOADING";
export const SET_EXCHANGE_RATE_ERROR = "SET_EXCHANGE_RATE_ERROR";
export const SET_EXCHANGE_RATES = "SET_EXCHANGE_RATES";

export const SET_BASKET_DB_DATA = "SET_BASKET_DB_DATA";

export const SET_BASKET_ID = "SET_BASKET_ID";
export const SET_BASKET_CURRENCY = "SET_BASKET_CURRENCY";
export const SET_BASKET_LOCATION = "SET_BASKET_LOCATION";

export const ADD_TO_BASKET_STATUS = "ADD_TO_BASKET_STATUS";
export const CREATE_BASKET_STATUS = "CREATE_BASKET_STATUS";
export const ADD_ITEM_TO_BASKET = "ADD_ITEM_TO_BASKET";

export const GET_BASKET_ITEMS_STATUS = "GET_BASKET_ITEMS_STATUS";
export const SET_BASKET_ITEMS = "SET_BASKET_ITEMS";
export const CALC_BASKET_TAX = "CALC_BASKET_TAX";
export const CALC_BASKET_TOTAL = "CALC_BASKET_TOTAL";
export const EDIT_BASKET_ITEM = "EDIT_BASKET_ITEM";
export const DELETE_BASKET_STATUS = "DELETE_BASKET_STATUS";
