export const SCANNER_READY_ONCE = "SCANNER_READY_ONCE";
export const SET_SCAN_DELAY = "SET_SCAN_DELAY";
export const SET_IS_SCAN_SUCCESS = "SET_IS_SCAN_SUCCESS";
export const SET_SCAN_RESULT = "SET_SCAN_RESULT";
export const SET_SCAN_ERROR = "SET_SCAN_ERROR";

export const GET_ITEM_LOADING = "GET_ITEM_LOADING";
export const GET_ITEM_ERROR = "GET_ITEM_ERROR";
export const SET_QR_ITEM = "SET_QR_ITEM";
export const SET_QR_LOCATION = "SET_QR_LOCATION";

export const SET_QTY = "SET_QTY";
export const SET_IS_INPUT_EMPTY = "SET_IS_INPUT_EMPTY";

export const GET_ITEM_LIKES_STATUS = "GET_ITEM_LIKES_STATUS";
export const SET_ITEM_LIKES = "SET_ITEM_LIKES";
export const GET_ITEM_REVIEWS_STATUS = "GET_ITEM_REVIEWS_STATUS";
export const SET_ITEM_REVIEWS = "SET_ITEM_REVIEWS";
