export const SET_IS_MENU_OPEN = "SET_IS_MENU_OPEN";

export const SET_IS_TOKEN_CALL_LOADING = "SET_IS_TOKEN_CALL_LOADING";
export const SET_TOKEN_CALL_ERROR = "SET_TOKEN_CALL_ERROR";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT = "LOGOUT";

export const SET_IS_LOGIN_LOADING = "SET_IS_LOGIN_LOADING";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";

export const SET_NAME = "SET_NAME";
export const SET_CURRENCY = "SET_CURRENCY";

export const SET_INITIALIZATION_STATUS = "SET_INITIALIZATION_STATUS";

export const SET_PROD_STATUS = "SET_PROD_STATUS";

export const SUPPORT_STATUS = "SUPPORT_STATUS";

export const RISK_TMP_LOGIN_INFO = "RISK_TMP_LOGIN_INFO";
