export const MY_ORDERS_STATUS = "MY_ORDERS_STATUS";
export const SET_MY_ORDERS = "SET_MY_ORDERS";

export const ORDER_DETAILS_STATUS = "ORDER_DETAILS_STATUS";
export const SET_ORDER_DETAILS = "SET_ORDER_DETAILS";
