export const PAYMENT_STAGE = "PAYMENT_STAGE";

export const PAY_WITH_CREDIT_CARD = "PAY_WITH_CREDIT_CARD";
export const PAY_WITH_PREPAID_CARD = "PAY_WITH_PREPAID_CARD";
export const PREPAID_AMOUNT_USD = "PREPAID_AMOUNT_USD";

export const ADD_CREDIT_CARD_STATUS = "ADD_CREDIT_CARD_STATUS";

export const GET_BYE_BYE_STATUS = "GET_BYE_BYE_STATUS";
export const SET_BYE_BYE = "SET_BYE_BYE";

export const GET_CARDS_STATUS = "GET_CARDS_STATUS";
export const SET_CARDS = "SET_CARDS";

export const SET_PAY_CARD_RESPONSE = "SET_PAY_CARD_RESPONSE";
export const PAY_CARD_STATUS = "PAY_CARD_STATUS";

export const SET_PROCESSED_ORDER = "SET_PROCESSED_ORDER";
export const PROCESS_ORDER_STATUS = "PROCESS_ORDER_STATUS";

export const SELECTED_CARD = "SELECTED_CARD";

export const SET_NEW_CARD_FORM = "SET_NEW_CARD_FORM";

export const SET_SIGNATURE = "SET_SIGNATURE";
export const BASKET_CONFIRMATION_STATUS = "BASKET_CONFIRMATION_STATUS";

export const SEND_ORDER_EMAIL_STATUS = "SEND_ORDER_EMAIL_STATUS";
